scripts/buildrunnerOSXCredStore

Fix resolve-config usage for python3

---

README.rst

Remove old, incorrect pip install details

---

.github/workflows/build.yaml
setup.py

Publish on every build of main for buildrunner

---

buildrunner/__init__.py
requirements.txt

Remove stack trace and include a better message if there's no VCS in the project, or in the case of git, when there isn't an initial commit

XENG-5493 Make error messages cleaner when VCS or git commit is missing

---

.github/workflows/build.yaml

A change to EnricoMi/publish-unit-test-result-action breaks test results publishing for python 3.6 builds, so we are skipping that step for that case
n/a
Build for python 3.6 fails
This is the test :)

Add conditional to test reults publish step

---

.github/workflows/build.yaml
buildrunner/sshagent/__init__.py
requirements.txt

Added support for Ed25519 keys, and simplified the code for loading all key types
n/a
Support more secure keys
A little

Add support for Ed25519 keys

---

README.rst

Update README to show recommended cache format first

Update README to show recommended cache format first

---

buildrunner/docker/runner.py
buildrunner/steprunner/tasks/run.py
tests/test_caching.py

Just adds more/clearer logging for caching to debug problems when caches don't work out properly.

Add better logging for caching

---

README.rst

A potential race condition needs to be documented
Race conditions are bad, and we like to avoid them - this will help people avoid this problem
This is not a change to code, just documentation

Add documentation about docker image build/tag/push race condition

---

.github/workflows/build.yaml
tests/test_caching.py

This also fixes the issue talked about in #37.

Move to pypa build instead of setuptools build

---

Dockerfile

Fixes docker image to actually be able to run now

Update dockerfile for python 3.11

---

.github/workflows/build.yaml
setup.py

Add version to the published docker image in github
The images are all tagged as _latest_ which makes reverting to previous working versions of the image difficult.
Setup a different branch on my forked repo and tested out very similar code to this PR, although not exact since the .git/workflows/build.yaml specifically calls out the adobe/main repo and branch.

Add version to published docker image

---

.github/workflows/build.yaml

Add git commit tag with current version

---

buildrunner/docker/multiplatform_image_builder.py
buildrunner/steprunner/tasks/build.py

Fix Dockerfile arg and formatted strings

---

buildrunner/docker/multiplatform_image_builder.py
buildrunner/steprunner/tasks/build.py

Fix setting docker_registry arg for multi-platform

---

README.rst
buildrunner/steprunner/tasks/build.py

Change multi-platform config to use platforms

---

buildrunner/docker/multiplatform_image_builder.py
buildrunner/steprunner/tasks/push.py
tests/test_multiplatform.py

Fix bug with MP images artifacts and enable parallel MP builds

---

buildrunner/__init__.py

The pypi push was not working since it was indented too far in a refactor. This fixes that.

Fix pushing for pypi builds

---

buildrunner/config.py
buildrunner/config_model.py
buildrunner/validation/config_model.py
buildrunner/validation/data.py
requirements.in
requirements.txt
tests/test_config_validation.py

Add config validation for multi-platform images

---

buildrunner/docker/multiplatform_image_builder.py
buildrunner/steprunner/tasks/build.py

Change failed image clean-up to warning and fix None path bug

---

buildrunner/validation/config_model.py
tests/test_config_validation.py

Allow a string for the build

---

buildrunner/steprunner/tasks/push.py

Add truncated digest to docker:platforms artifact

---

buildrunner/docker/multiplatform_image_builder.py
buildrunner/steprunner/tasks/build.py
tests/test-files/multiplatform/Dockerfile.none.path
tests/test-files/multiplatform/buildrunner-path-test.txt
tests/test-files/multiplatform/buildrunner.yaml
tests/test-files/test-multi-platform-none-path.yaml

Refactor and add test for MP builds when path is not specified.

Revert build path for single platform builds.

---

README.rst
buildrunner/config.py
buildrunner/validation/step.py
tests/test_config_validation/test_validation_config.py
tests/test_config_validation/test_validation_step.py

Fixed dns-search documentation error. And cleaned up a few other config validation things which was found.

Update config validation

---

buildrunner/validation/step.py

Move caches validation to be under services and run

---

buildrunner/docker/multiplatform_image_builder.py

Increase MP build retry timeout

---

buildrunner/docker/multiplatform_image_builder.py

Add backoff to MP build retries

---

buildrunner/docker/builder.py
buildrunner/steprunner/tasks/build.py
tests/test-files/test-general.yaml
tests/test_caching.py

When running unit tests it became apparent that there were many dangling images left behind as well as a few containers which weren't removed. These minor changes cleans all of that up.

Clean up lingering images and containers

---

README.rst
buildrunner/__init__.py
buildrunner/cli.py
buildrunner/docker/multiplatform_image_builder.py
buildrunner/steprunner/tasks/build.py
buildrunner/validation/config.py
tests/test-files/test-multi-platform-inject.yaml

Add command line flag to override platforms configuration to only build a single platform image build.

Add single platform image flag

---

buildrunner/__init__.py
buildrunner/docker/multiplatform_image_builder.py
buildrunner/validation/step.py
tests/test_config_validation/test_validation_artifacts.py
tests/test_config_validation/test_validation_run.py

Bugfix change for failing artifacts and revert MP build retries params

---

buildrunner/__init__.py
buildrunner/docker/multiplatform_image_builder.py
buildrunner/steprunner/tasks/build.py
tests/test_multiplatform.py

Just some minor tweaks to fix issues I noticed.

Fix references to docker registry image and fix docs

---

buildrunner/docker/multiplatform_image_builder.py
buildrunner/steprunner/tasks/build.py
buildrunner/validation/config.py
buildrunner/validation/step.py
tests/test_config_validation/test_validation_step.py
tests/test_multiplatform.py

Add no-cache, cache_from and pull MP build params

---

README.rst
buildrunner/config.py
tests/test-files/test-env-vars.yaml
tests/test_buildrunner_files.py

Adds the `env` instance in Jinja.
See #102.
I added env vars across all test files, then checked for the env vars (one starting with BUILDRUNNER_, the other arbitrarily named) in one of the test files.

Fixes #102, adds support for env instance in jinja

---

buildrunner/__init__.py
buildrunner/cli.py
buildrunner/docker/multiplatform_image_builder.py
tests/test_multiplatform.py
tests/test_runner.py

Add cleanup_images argument and deprecate keep_images

---

buildrunner/steprunner/__init__.py
tests/test-files/test-local-images-and-platform.yaml
tests/test_buildrunner_files.py

Fixed a bug where buildrunner crashes when --local-images or --platform is passed in the cli args.

Bugfix platform and local-images cli args

---

buildrunner/config.py
tests/test_config_validation/test_retagging.py

Bugfix for tagging docker images with default tag

Fix appending default tag

---

tests/test_config_validation/test_retagging.py

Generalized test configs

---

README.rst
buildrunner/__init__.py
buildrunner/cli.py
buildrunner/config/__init__.py
buildrunner/config/loader.py
buildrunner/config/models.py
buildrunner/docker/multiplatform_image_builder.py
buildrunner/docker/runner.py
buildrunner/loggers.py
buildrunner/steprunner/tasks/build.py
buildrunner/steprunner/tasks/push.py
buildrunner/steprunner/tasks/run.py
docs/global-configuration.rst
setup.py
tests/test_cli.py
tests/test_config_validation/test_global_config.py
tests/test_config_validation/test_retagging.py
tests/test_loggers.py
tests/test_push_security_scan.py

This implements security scanning for all pushed docker images depending on configuration in global config + config on the command line.

Add docker image security scanning with trivy

---

setup.py

Fixes handling for a bad dependency.

Replace jaraco classes in setup.py requirements

---

README.rst
buildrunner/config/models_step.py
buildrunner/docker/builder.py
buildrunner/docker/multiplatform_image_builder.py
buildrunner/steprunner/tasks/build.py
setup.py
tests/test-files/test-multi-stage.yaml
tests/test_multiplatform.py

Allows you to stop at a specific build stage in multi-stage builds.
See https://docs.docker.com/build/building/multi-stage/#stop-at-a-specific-build-stage
XENG-7690

XENG-7690 Allow targeting a stage to build for multi-stage builds

---

README.rst
buildrunner/config/__init__.py
tests/test-files/test-general.yaml

Simplify env var name to just ARCH

---

buildrunner/config/fetch/__init__.py
buildrunner/config/fetch/file.py
buildrunner/config/fetch/github.py
buildrunner/config/fetch/http.py
buildrunner/config/models.py

Fixes issues with the new config refactor and using github file redirects which still expected dicts and not pydantic models.
github file redirects threw errors
github file redirects work properly

XENG-7766 Fix github file redirects with new global config

---

buildrunner/cli.py

Fix clean_cache

---

buildrunner/docker/runner.py
buildrunner/steprunner/tasks/run.py
buildrunner/utils.py

Added additional checks and logging for artifact caching.
In our build system there some projects which experiences apparent issues with the buildrunner caching. Attempts to reproduce the issue have failed. These changes won't fix these issues but it is hopeful that it will provide additional insight into what is causing the issue.

Add additional checks and logs for artifact caching

---

buildrunner/docker/builder.py

The .dockerignore is ignored when building single platform images. This provides a fix for that only when the config is also not injecting other files into the context. In the case that it is injecting files the .dockerignore will be ignored like it is now, but it will log a warning stating that the .dockerignore will be ignored.
A follow up internal Adobe ticket has been created to refactor buildrunner to remove this inject limitation.

Fix single platform builds to use .dockerignore

---

README.rst
buildrunner/__init__.py
buildrunner/config/models.py
buildrunner/docker/builder.py
buildrunner/sshagent/__init__.py
buildrunner/steprunner/tasks/build.py
setup.py
tests/test_builders.py
tests/test_config_validation/test_global_config.py

Add use-legacy-builder flag to config. Set legacy builder to be the default.

---

buildrunner/docker/multiplatform_image_builder.py
setup.py
tests/test_multiplatform.py
tests/test_push_artifact.py

Refactor push retries

---

buildrunner/SourceDockerfile
buildrunner/__init__.py

Create unique source image layer

---

buildrunner/docker/builder.py

Fix small bug when the build is broken.

Fix image reference

---

README.rst
examples/README.rst

Update examples README files

---

buildrunner/docker/runner.py
buildrunner/steprunner/tasks/run.py
examples/run/cmd/buildrunner.yaml
examples/run/cwd/buildrunner.yaml
examples/run/dns/buildrunner.yaml
examples/run/dns_search/buildrunner.yaml
examples/run/env/buildrunner.yaml
examples/run/files/buildrunner.yaml
examples/run/files/data.txt
examples/run/hostname/buildrunner.yaml
examples/run/image/buildrunner.yaml
examples/run/ports/buildrunner.yaml
examples/run/provisioners/buildrunner.yaml
examples/run/provisioners/my_script.sh
examples/run/pull/buildrunner.yaml
examples/run/shell/buildrunner.yaml
examples/run/systemd/buildrunner.yaml
examples/run/systemd_cgroup2/buildrunner.yaml
examples/run/user/buildrunner.yaml
examples/run/volumes_from/buildrunner.yaml

Adds run example files. Discovered and fixed bugs in dns and provisioners code.

Add run examples and bugfix dns and provisioners

---

buildrunner/__init__.py
examples/commit/buildrunner.yaml
examples/push/buildrunner.yaml

Add push and commit examples

---

examples/depends/buildrunner.yaml
examples/run/caches/buildrunner.yaml
tests/test_buildrunner_files.py

Add depends and run/caches example

Add depends example

---

README.rst
docs/development.rst
docs/installation.rst

Update documentation
- [x ] I have updated the documentation or no documentation changes are required.

Update installation and development documentation

---

buildrunner/steprunner/tasks/run.py

XENG-8957 Add labels to docker networks

---

buildrunner/steprunner/tasks/run.py

XENG-8957 Add logging around network creation and deletion

---

pyproject.toml

XENG-8985 Fix incorrect test requirements file reference

---

pyproject.toml

XENG-8985 Reference version file directly in pyproject.toml

---

buildrunner/config/loader.py

Fix issue parsing version
