- buildrunner/steprunner/tasks/run.py
- tests/test-files/test-general.yaml
The format:uncompressed property was being removed after the first directory was added to artifacts
> Fix format:uncompressed only leaving one directory uncompressed

- README.rst
- buildrunner/__init__.py
- buildrunner/docker/builder.py
- buildrunner/sshagent/SSHAgentProxyImage/Dockerfile
- tests/runservicecontainer/Dockerfile
- tests/test-files/test-general.yaml
- tests/test-files/test-ssh.yaml
- tests/test-files/test-systemd.yaml
- tests/webservicecontainer/Dockerfile
Adds the temporary directory configured in global config (or via env var). 
There is a temp_dir configuration property in the global config, but it is not respected for certain usages, especially building the source docker image which can be quite large. After modifying this, I noticed that centos:8 images no longer work properly due its deadness. Really, it's very dead. I ported to rockylinux 8 instead which is bug-for-bug compatible.
It is a non-invasive change that will need to be tested by the person who first saw signs of the bug. The build will test the rockylinux portions of the changes.
> Add temp dir to docker builder, move to rocky linux

- scripts/buildrunnerOSXCredStore
docker sock variable wasn't being used
> using docker_sock variable

- README.rst
- buildrunner/__init__.py
We did not currently expose the VCSINFO_RELEASE variable, even though vcsinfo provides it. This adds support for it.
I needed the VCSINFO_RELEASE variable accessed from a built component.
I installed the latest code and ensured it was present.
> Add VCSINFO_RELEASE and update docs

- README.rst
- buildrunner/__init__.py
- tests/config-files/dot-buildrunner.yaml
- tests/test-files/test-env-vars.yaml
Adds support for global environment variables in the buildrunner global config file. 
n/a
This allows supporting additional use cases such as providing secret credentials via env vars to every buildrunner build on a system. It is currently needed for improving a buildrunner yaml file that is used across many builds on local and build server systems.
I installed the code locally and tested the functionality. I also added a functional test via a buildrunner test file.
> Add support for global env vars

- buildrunner/docker/runner.py
- buildrunner/utils.py
- requirements.in
- requirements.txt
- tests/test_utils_flock.py
Add timeout to file locking around saving and restoring caches. Add acquire and release lock functions in utils.py
Some Jenkins jobs appear to be deadlocked around the existing file lock with caching. This is meant to lessen the pain of when deadlocks occur by allow other jobs to run. This doesn't address the root cause of the deadlocks however.
Unit tests were added around the new file lock timeout functions in utils
> Add timeout to file locking around saving and restoring caches.

- tests/test-files/test-general.yaml
- tests/test-files/test-inject-nonexistent-dir.yaml
- tests/test_buildrunner_files.py
Fixed buildrunner tests to use temporary directory for the buildrunner results directory. Moved a failing step in a buildrunner test file, which was attempting to inject a nonexistent directory.
> Fix buildrunner file tests to use TemporaryDirectory for buildrunner results

- buildrunner/steprunner/tasks/run.py
- tests/test-files/test-unsafe-git.yaml
Newer versions of git can complain about an unsafe `/source` dir if the owner of the directory is different than the current owner. See https://github.blog/2022-04-12-git-security-vulnerability-announced/#cve-2022-24765 for more info. This is not applicable to buildrunner invocations since they are run in docker images specified by the user. Therefore we always mark the git directory as safe before any commands are executed. This may not catch ALL cases where it is needed (i.e. entrypoint of the image triggers the issue), but it should cover a majority of cases. Any other cases will need to be handled by the user in their images by using the same (or similar) `git config` command.
See the description above for context.
A functional test file was added that triggers the behavior. Without …
> Ensure that the source dir is marked safe for newer versions of git

- README.rst
- buildrunner/steprunner/tasks/pypipush.py
Support pushing wheels as well as sdist packages for python.
n/a
Python builds using the `build` module build wheels as well as sdist packages by default. This helps support the use case more easily.
I conducted manual testing since pypi testing cannot be tested in automated testing.
> Add support for pushing python wheels

- README.rst
- buildrunner/__init__.py
- buildrunner/docker/multiplatform_image_builder.py
- buildrunner/steprunner/__init__.py
- buildrunner/steprunner/tasks/__init__.py
- buildrunner/steprunner/tasks/build.py
- buildrunner/steprunner/tasks/push.py
- requirements.in
- requirements.txt
- tests/test-files/multiplatform/Dockerfile
- tests/test-files/multiplatform/buildrunner.yaml
- tests/test_multiplatform.py
Adds support for docker multi-platform images using docker buildx. Because a common use case in buildrunner is to build a image locally, run some tests in the new image and then push the newly built image to a remote registry if the tests pass some specially steps had to be taken. In it's simplest form you can do `docker buildx build --platform <list of platforms> -t <tag> --push .` which will build and push a multi-platform image in a single command (but you may need to create a new builder for this). However, using this way will not allow for intermediate testing on the image prior to pushing it to a remote registry. For this reason the following methodology was contrived:
1. Start a ephemeral local docker registry container
2. Build each image for each platform with unique temporary …
> Add support for multi-platform images

- buildrunner/docker/__init__.py
- buildrunner/docker/builder.py
- buildrunner/docker/multiplatform_image_builder.py
- buildrunner/steprunner/tasks/push.py
- tests/test-files/test-docker-pull-failure.yaml
- tests/test-files/test-mp-image-reuse.yaml
- tests/test_buildrunner_files.py
- tests/test_runner.py
Add test for multiplatform image reuse in other steps.
> Add inject dockerfile support for multiplatform images and test for mp image reuse in other steps.

- Dockerfile
Replacing semi-colons with && in the Dockerfile ensures that if any of the commands fail then the Docker build will fail.
> Replace ';' with '&&' in Dockerfile

- buildrunner/docker/multiplatform_image_builder.py
- requirements.in
- requirements.txt
An intermittent MP build failure occurs on build nodes. With a docker exception and error message similar to these:
> 16:07:27  #19 ERROR: Get "http://localhost:33321/v2/": read tcp [::1]:35204->[::1]:33321: read: connection reset by peer
> 16:07:27  ------
> 16:07:27   > pushing localhost:33321/buildrunner-mp-containerize-pr-125-265.i0fac61.m0-1-linux-arm64-v8:latest with docker:
> 16:07:27  ------
> 16:07:27  ERROR: Get "http://localhost:33321/v2/": read tcp [::1]:35204->[::1]:33321: read: connection reset by peer
This occurs on building MP images. And when retrying the build it does eventually successfully build. This is a quick fix until a deeper investigation can be completed.
> Add retries on multi-platform image builds

- buildrunner/docker/multiplatform_image_builder.py
Provides more log information when the multi-platform image builds fails and also changed the settings a little bit. Hopefully these changes will improve the intermittent MP build failures we have seen. But if not, it should provide some additional log information that could be helpful.
> Change MP retry settings and add logging on failures

- buildrunner/validation/step.py
This fixes duplicated None references when Optional will suffice.
Just making the code more pythonic (one right way to do things).
> Fix usages of union in config validation

- buildrunner/docker/multiplatform_image_builder.py
- buildrunner/steprunner/tasks/build.py
- tests/test_multiplatform.py
Bugfix for intermittent multi-platform build failures
> Bugfix for intermittent multi-platform build failures

- buildrunner/validation/config.py
- buildrunner/validation/step.py
> Bugfix validation 'env' can be any type (#6)

- buildrunner/config.py
Fixes crash issue when there is a blank global buildrunner config file. (i.e. ~/.buildrunner.yaml)
> Fix blank global buildrunner config crash

- README.rst
- buildrunner/__init__.py
- buildrunner/docker/multiplatform_image_builder.py
- buildrunner/validation/config.py
This adds the ability to specify a builder for a specific platform when doing multiplatform builds.
Buildx does not seem to make this easy to define default builders per platform with a fallback to the default builder when there is no platform-specific builder. This implements this same ability in buildrunner instead.
I have manually tested this code to ensure that it is performing correctly. This is very difficult to test in automated fashion since it involves messing with the buildx builders which is non-trivial for automated builds.
> Allow specifying builders for specific platforms in global config

- buildrunner/docker/multiplatform_image_builder.py
- tests/test_multiplatform.py
Adds support for building on remote builders that cannot access the local registry.
When using remote builders, they cannot access the temporary local registry since it runs on localhost. Attempting to do with fully qualified names is also problematic unless we set up full certs, auth, etc. To prevent this, we can simply --load instead of --push'ing in the buildx build, then push the resulting image for the final manifest creation.
I tested this in a development environment to ensure it does as expected.
> Use load instead of push to support remote builders

- buildrunner/docker/multiplatform_image_builder.py
- tests/test_multiplatform.py
This removes the `push` flag that was never unset when building multiplatform images. It also adds some testing to ensure that things are working correctly in mocking.
Simplification and better testing was desired.
> Simplify and add additional tests for mp building

- buildrunner/steprunner/tasks/build.py
The current release of buildrunner shows an error when building multiplatform images. This error is ignored and everything works fine, it just makes people think that something actually went wrong. This fixes that.
The error is related to trying to cleanup images that were built. Since multiplatform images are built differently than single platform images and cleaned up differently as well, we just need to not do the code that handles cleaning up images when building multiplatform.
I tested this manually on a build agent.
> Prevent no resource to delete error

- buildrunner/__init__.py
- buildrunner/docker/multiplatform_image_builder.py
- tests/test_multiplatform.py
Add more output logging for multiplatform builds. Example output:
```
==> Running step: push-container:build
Pull was not specified in configuration, defaulting to True
Running docker build
-----------------------------------------------------------------
Note: Building multi-platform images can take a long time, please be patient.
If you are running this locally, you can speed this up by using the '--disable-multi-platform' CLI flag or set the 'disable-multi-platform' flag in the global config file.
-----------------------------------------------------------------
Starting builds for 2 platforms in parallel
Building image for platform linux/arm64 with arm1 builder
Building image for platform linux/amd64 with default builder
```
I had a hard time telling if ARM builds were running on the …
> Add more output logging for multiplatform builds

- buildrunner/__init__.py
- buildrunner/docker/multiplatform_image_builder.py
- tests/test_multiplatform.py
The log writer cannot be pickled to be used in multiprocess builds, and therefore is broken most of the time. Using print prevents that. This fixes a bug introduced with the last release.
> Move back to print for logging to console in multiplatform builder

- buildrunner/docker/multiplatform_image_builder.py
- tests/test-files/test-multi-platform-inject.yaml
Injecting a dir results in a failure since shutil.copy cannot handle dirs.
This fixes the bug to correctly inject dirs.
I added a unit test to verify correct behavior.
> Fix problems with injecting a dir in multiplatform build

- README.rst
- buildrunner/__init__.py
- setup.py
- tests/test-files/test-general.yaml
Adds an environment variable for buildrunner.yaml files to be able to tell the underlying architecture of the system that buildrunner is running on (i.e. ARM, AMD, etc).
There is no way, currently, to tell the underlying architecture of the current machine that buildrunner is running on (i.e. ARM vs AMD). This adds an env var to be able to tell that, which can then be used in the buildrunner.yaml file to mark built artifacts as being for one platform vs another.
I added a test step in the test files to ensure that the platform is being set to something and it errors if it is not set (tested locally without this change and with this change and it works properly).
> Add env var for platform of underlying device

- buildrunner/__init__.py
- buildrunner/docker/multiplatform_image_builder.py
- buildrunner/steprunner/tasks/push.py
- tests/test-files/test-multi-platform-image-reuse.yaml
This removes the multiprocessing from pushing images, which really isn't needed as we can fail other ways there.
I noticed failures when pushing multiple repos from a multiplatform build. Most concerning was that the build acted like everything was ok when it really failed to push at least one of the images. 
I've added a functional test file, though this doesn't completely exercise the code in question, it should be closer to what actually happens.
> Improve fail and retry logic when pushing images

- buildrunner/__init__.py
Use the default cache directory if there are any errors with the cache root dir in the global config. Rather than failing the build, this will print warnings of the failures with the directory and proceed with the building using the default cache directory on the local file system.
> Use default cache dir if there are errors with configured cache dir

- .pylintrc
- README.rst
- buildrunner/__init__.py
- buildrunner/config.py
- buildrunner/docker/multiplatform_image_builder.py
- buildrunner/steprunner/tasks/build.py
- buildrunner/validation/config.py
- tests/test_buildrunner_files.py
- tests/test_config_validation/test_validation_step.py
- tests/test_multiplatform.py
Add support for cache_from/cache_to parameters for docker buildx (multiplatform) builds.
We would like to add more caching for docker, and this is one available option for us. This does not solve all problems as it only works for buildx builds (which are used in multiplatform builds) and also only specific buildx builder drivers (container and remote is what has been tested so far), but it is a start.
I have run this against multiple builders in different configurations and confirmed that the build cache directory is created locally (even when using a remote builder).
> Add cache_from and cache_to support for multiplatform builds

- buildrunner/__init__.py
- buildrunner/docker/image_info.py
- buildrunner/docker/multiplatform_image_builder.py
- buildrunner/steprunner/tasks/__init__.py
- buildrunner/steprunner/tasks/build.py
- buildrunner/steprunner/tasks/push.py
- tests/test_image_info.py
- tests/test_multiplatform.py
Refactors the multiplatform image build code to simplify usage of image refs/tags/names and to prevent errors throughout the codebase.
The many "tagged_names", "tags", "names", etc variable names were quite confusing and difficult to work with. Additionally, tags should not be able to be specified when building a multiplatform image. Only later when the image is tagged/committed/pushed should it take arbitrary tags. This code simplifies all of these usages to create a simple image info tracking class for both the built images and the final tagged images, and makes it clear which properties belongs to each and which should be used in certain places.
I tested this locally with a test repository. It still needs more testing and the unit tests passing before it can be merged.
> Refactor multiplatform image builder image handling code

- README.rst
- buildrunner/__init__.py
- buildrunner/config.py
- buildrunner/docker/multiplatform_image_builder.py
- buildrunner/validation/config.py
- tests/test_multiplatform.py
Using a local build registry for multiplatform builds can be quite slow as it pushes large images to the local registry. This allows users to use an arbitrary registry and benefit from caches, etc. This also allows multiplatform builds to occur on disparate systems without too much trouble.
See above
I tested this minimally locally. It definitely needs further testing and unit tests written to cover it.
> Add support for arbitrary build registries in multiplatform builds

- README.rst
- buildrunner/validation/config.py
- buildrunner/validation/step_images_info.py
- tests/test-files/test-multi-platform-image-reuse.yaml
- tests/test_config_validation/Dockerfile.retag
- tests/test_config_validation/test_multi_platform.py
- tests/test_config_validation/test_retagging.py
- tests/test_config_validation/test_validation_step.py
Performs configuration validation checks on multi-platform builds to ensure that re-tagging built multi-platform images in a subsequent step is not allowed. This is because non-deterministic behavior can occur if re-tagging is allowed.
> Implement multi-platform re-tag config validation

- buildrunner/__init__.py
- buildrunner/config.py
- buildrunner/steprunner/tasks/push.py
- tests/test_config_validation/test_retagging.py
Add more config validation. This change adds  multi-platform re-tagging checking for BUILDRUNNER_BUILD_DOCKER_TAG and jinja template in the config file.
> Add check and tests for automatic buildrunner id image tag

- buildrunner/validation/config.py
- tests/test_config_validation/test_retagging.py
Handle retagged image validation when the retagging step is also multiplatform.
The multiplatform retagging validation did not account for multiplatform steps doing the retagging, which is a valid use case.
Unit tests.
> Handle cases where multi-platform images are retagged in a mp step

- buildrunner/docker/runner.py
Adds retries around the cache funtionality.
On occasion it has timed out in certain areas with the cache. And re-running the build it will be successful.
Fails when it times out with the cache.
If a cache timeout occurs it will retry it one time. Then fail if the 2nd try times out as well or another exception occurs.
> Add retry around writing and loading cache

- buildrunner/steprunner/tasks/run.py
Failed builds would sometimes cause corrupted causes to be saved and therefore cause all subsequent builds to fail in the same way. This prevents that issue by never saving the cache if the run fails for any reason.
> Do not save caches for a failed build

- README.rst
- buildrunner/config/loader.py
- buildrunner/config/models_step.py
- buildrunner/config/validation.py
- buildrunner/docker/builder.py
- setup.py
- tests/test-files/test-push.yaml
- tests/test_config_validation/test_multi_platform.py
- tests/test_config_validation/test_retagging.py
The default tag can conflict sometimes with multiple repositories named the same but with different tags. This allows that use case.
Multiplatform builds would error if the same repo was used with different tags for different steps.
There is no error in this case.
> XENG-7748 Add flag to disable default tag

- README.rst
- buildrunner/config/__init__.py
- tests/test-files/test-general.yaml
BUILDRUNNER_PLATFORM was poorly named, it needs to be BUILDRUNNER_ARCHITECTURE instead. This deprecates platform in favor of architecture.
> Rename platform to architecture for env var

- README.rst
- buildrunner/config/models.py
- buildrunner/config/models_step.py
- buildrunner/steprunner/tasks/push.py
- docs/global-configuration.rst
- setup.py
- tests/test-files/test-security-scan.yaml
- tests/test-files/test-xfail-security-scan.yaml
- tests/test_buildrunner_files.py
- tests/test_config_validation/test_models.py
- tests/test_push_security_scan.py
Adds security scan overrides at the step level and fixes an issue when add_build_tag is false.
When add_build_tag is false, the default tag doesn't exist and the security scan breaks.
Broken security scan
Working security scan
> Add overrides for security scanning at the step level and fix handling for no build tag

- requirements.txt
When I was trying to install buildrunner I was getting errors about being unable to install wheel on pyyaml I think that this is because pyyaml 6.0 [isn't available for python 3.12](https://www.piwheels.org/project/pyyaml/)
Updating it to 6.0.1 made it so that I could install and I've been able to successfully build as well.
Being able to install buildrunner
Collecting pyyaml==6.0 (from buildrunner)
Using cached PyYAML-6.0.tar.gz (124 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [54 lines of output]
success
- [-] I have added tests to cover my changes.
- [-] I have updated the base version in ``setup.py`` (if appropriate).
> Upgrading pyyaml to 6.0.1

- README.rst
- buildrunner/config/models_step.py
- buildrunner/steprunner/tasks/run.py
- setup.py
- tests/test-files/test-push-artifact.yaml
- tests/test_config_validation/test_validation_artifacts.py
- tests/test_push_artifact.py
Add ability to rename artifacts which match artifacts exactly. Renaming of wildcard matches of artifacts is not supported in this PR.
There are situations where artifacts with the same base name overwrite each other in the artifacts output directory.
> Add rename artifact functionality

- buildrunner/docker/runner.py
- buildrunner/loggers.py
- buildrunner/utils.py
- tests/test_caching.py
- tests/test_utils_flock.py
Fixes this error:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.11/threading.py", line 982, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.11/site-packages/buildrunner-3.8.999-py3.11.egg/buildrunner/steprunner/tasks/run.py", line 609, in attach_to_service
service_runner.attach_until_finished(service_logger)
File "/usr/local/lib/python3.11/site-packages/buildrunner-3.8.999-py3.11.egg/buildrunner/docker/runner.py", line 630, in attach_until_finished
stream.write(line)
File "/usr/local/lib/python3.11/site-packages/buildrunner-3.8.999-py3.11.egg/buildrunner/loggers.py", line 179, in write
output = str(output, encoding=sys.stdout.encoding, …
```
> Fix issue with logging in docker image

- buildrunner/docker/multiplatform_image_builder.py
- setup.py
- tests/test_multiplatform.py
This update logs the output for buildx which is used to build multiplatform images. Also while building multipltform images uses threading instead of multiprocessing.
> Log Buildx output and use threading instead of multiprocessing

- buildrunner/docker/multiplatform_image_builder.py
- buildrunner/steprunner/tasks/run.py
- tests/test-files/test-general-buildx.yaml
Add buildx support for post-build. 
Buildx requires a named images and not just SHA digests of the image in the dockerfile. This adds a tag the run image before the post-build and then removes it.
> Add support for post-build with buildx builder

- buildrunner/__init__.py
- buildrunner/docker/multiplatform_image_builder.py
- setup.py
- tests/test-files/test-push-artifact-buildx.yaml
- tests/test-files/test-push-artifact-legacy.yaml
- tests/test_push_artifact.py
Add use-legacy-builder flag to the get_source_image method. This is another step to eventually remove dependency on the legacy image builder.
> Add buildx builder support to get_source_image method

- buildrunner/docker/daemon.py
- tests/test_push_artifact.py
Fixes the intermittent test failures of "404 Client Error for http+docker://localhost/v1.45/containers/create: Not Found ("No such image: busybox:latest")". Prior to this PR there are some tests that would occasionally fail and retrying the test would often resolve the issue.
> Fix intermittent test failures for missing busybox image

- buildrunner/__init__.py
- buildrunner/docker/daemon.py
- tests/test_runner.py
> Only pull docker daemon proxy image in tests

- buildrunner/__init__.py
- buildrunner/docker/__init__.py
- buildrunner/docker/builder.py
- buildrunner/docker/daemon.py
- buildrunner/docker/importer.py
- buildrunner/docker/runner.py
- buildrunner/sshagent/__init__.py
- buildrunner/steprunner/tasks/build.py
- buildrunner/steprunner/tasks/push.py
- buildrunner/steprunner/tasks/run.py
> Mark docker-py calls

- .github/workflows/build.yaml
- buildrunner/__init__.py
- buildrunner/sshagent/__init__.py
- buildrunner/steprunner/__init__.py
- buildrunner/steprunner/tasks/run.py
- tests/test-files/test-ssh-buildx.yaml
- tests/test_builders.py
> Add buildx builder support to get_ssh_agent_image

- buildrunner/__init__.py
Add retries around the archive tarfile.
Minimizes the possibility of an error when multiple buildrunner processes are running concurrently in the same directory. It still possible but is less likely.
> 15:35:31  Traceback (most recent call last):
> 15:35:31    File "/bin/buildrunner", line 14, in <module>
> 15:35:31      sys.exit(cli.main(sys.argv))
> 15:35:31    File "/usr/lib64/buildrunner/lib/python3.9/site-packages/buildrunner/cli.py", line 414, in main
> 15:35:31      build_runner.run()
> 15:35:31    File "/usr/lib64/buildrunner/lib/python3.9/site-packages/buildrunner/__init__.py", line 373, in run
> 15:35:31      self.get_source_archive_path()
> 15:35:31    File "/usr/lib64/buildrunner/lib/python3.9/site-packages/buildrunner/__init__.py", line 261, in get_source_archive_path
> …
> Add retries on creating archive tar

- buildrunner/__init__.py
Increase retry params for creating archive tar. The failures are still occurring but are less frequent.
> Increase retry params for creating archive tar

- .github/workflows/build.yaml
- buildrunner/__init__.py
- pytest.ini
- scripts/combine_xml.py
- tests/test_buildrunner_files.py
- tests/test_caching.py
- tests/test_multiplatform.py
- tests/test_push_artifact.py
> Add parallel tests to Github actions workflow

- buildrunner/docker/runner.py
- tests/test_caching.py
> Replace stop/start with python-on-whales

- buildrunner/steprunner/tasks/push.py
- tests/test_push_security_scan.py
Just a quick fix to ensure that the trivy cache dir is set correctly (in case they ever change the default)
> Make sure to explicitly set cache-dir just in case

- buildrunner/__init__.py
- buildrunner/config/models.py
- buildrunner/docker/__init__.py
- buildrunner/docker/builder.py
- buildrunner/docker/daemon.py
- buildrunner/docker/importer.py
- buildrunner/docker/runner.py
- buildrunner/sshagent/__init__.py
- buildrunner/steprunner/tasks/run.py
- tests/test_builders.py
Add python on whales options for import_image, remove_image and remove_container.
> Convert to python on whales part2

- .github/workflows/build.yaml
- tests/config-files/dot-buildrunner.yaml
- tests/test-files/test-ssh-buildx.yaml
- tests/test-files/test-ssh.yaml
- tests/test_buildrunner_files.py
The deploy key being installed on the buildrunner repository is deemed a security risk (even though the repo is public and only read only access was granted to the key). This moves to using a temporary ssh key generated during testing only and used only on a temporary SSH daemon.
Used bad deploy key that is now invalidated
SSH keys are automatically handled
> Remove deploy key usage and instead use temporary SSH key

- buildrunner/utils.py
- requirements.in
- requirements.txt
This PR converts fcntl to portalocker to be windows compatible. Fcntl does not work on non-Unix machines. Portalocker works on both Unix and Windows machines.
> Convert fcntl to portalocker to be windows compatible

- buildrunner/__init__.py
- buildrunner/docker/__init__.py
- buildrunner/docker/builder.py
- buildrunner/docker/daemon.py
- buildrunner/docker/importer.py
- buildrunner/docker/runner.py
- buildrunner/sshagent/__init__.py
- buildrunner/steprunner/tasks/build.py
- buildrunner/steprunner/tasks/run.py
- tests/test_builders.py
- tests/test_buildrunner_files.py
- tests/test_caching.py
Rollback previous attempts to convert `docker-py` calls with `python-on-whales`, except for building multi-platform images which is not possible with `docker-py`. It was determined that the pitfalls and current limitations with python-on-whales that it was worth the effort to convert totally over to it at this time. The PR rollbacks those changes in a single commit to make the code more concise and readable.
> Rollback python_on_whales conversion

- Dockerfile
- README.rst
- buildrunner/config/models_step.py
- buildrunner/docker/runner.py
- buildrunner/steprunner/tasks/run.py
- setup.py
- tests/test-files/test-systemd.yaml
Systemd v248+ requires new parameters to work correctly with docker. These are documented in https://github.com/moby/moby/issues/42275.
It adds support for a new config flag to enable the new behavior.
Hard failure when using the systemd flag with v248+
systemd works correctly
> Add support for systemd v248+

- README.rst
- buildrunner/config/models_step.py
- buildrunner/docker/runner.py
- buildrunner/steprunner/tasks/run.py
- tests/test-files/test-systemd.yaml
Renames systemd v248 flags to systemd cgroup2, since that's really what it is about. Also adds a check to make sure it will work properly on linux systems.
> Improve cgroup v2 support

- buildrunner/__init__.py
- tests/test-files/test-docker-pull-failure.yaml
Currently container errors (and other unknown errors) show a successful build, but this should fail with an error message and potentially a traceback if the exception is unhandled explicitly.
> Handle container errors correctly

- buildrunner/__init__.py
- buildrunner/cli.py
- buildrunner/config/__init__.py
- buildrunner/docker/runner.py
- setup.py
- tests/test_caching.py
- tests/test_config_validation/test_container_labels.py
Adds the capability to automatically add labels to all containers started with buildrunner. This will track down bag agents that do not clean up properly, etc.
Internal issue only
> Add ability to label all started containers

- buildrunner/docker/__init__.py
Adds a check to see if the docker daemon is running. If the daemon is not running it will print the exception with a message to check that the docker daemon is running and try again.
Without this check when you run buildrunner without the docker daemon running you get a vague error message.
Without this check when you run buildrunner without the docker daemon running you get the following vague error message:
> docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
Now when you run buildrunner without the docker daemon running you get the following message:
>  buildrunner.docker.BuildRunnerContainerError: Error connecting to Docker daemon. Please ensure the Docker daemon is running and try again.
> Check for running docker daemon

- .gitignore
- README.rst
- examples/README.rst
- examples/build/basic/buildrunner.yaml
- examples/run/basic/buildrunner.yaml
- tests/test_buildrunner_files.py
Adds the basic structure to add example buildrunner configuration files, update and add docs, and runs the new configs in the unit tests.
> Add Examples

- buildrunner/__init__.py
- buildrunner/docker/daemon.py
- buildrunner/sshagent/__init__.py
- buildrunner/steprunner/__init__.py
- buildrunner/steprunner/tasks/run.py
The --container-labels parameter is not passed to the daemon or ssh-agent containers when created
Container labels missing from containers associated with build
> Pass docker container labels to daemon and ssh-agent container creation

- .gitignore
- README.rst
- examples/README.rst
- examples/build/basic/buildrunner.yaml
- examples/build/buildargs/buildrunner.yaml
- examples/build/cache/buildrunner.yaml
- examples/build/import/buildrunner.yaml
- examples/build/inject/buildrunner.yaml
- examples/build/inject/injectfile.txt
- examples/build/platform/README.rst
- examples/build/platform/buildrunner.yaml
- examples/build/platforms/README.rst
- examples/build/platforms/buildrunner.yaml
- examples/run/basic/buildrunner.yaml
- examples/run/services/Dockerfile
- examples/run/services/buildrunner.yaml
- examples/run/services/standalone-buildrunner.yaml
- run-buildrunner.sh
- tests/test_buildrunner_files.py
> Build Examples

- README.rst
- buildrunner/docker/daemon.py
- buildrunner/docker/runner.py
- buildrunner/sshagent/__init__.py
- buildrunner/steprunner/__init__.py
- buildrunner/steprunner/tasks/run.py
- tests/runservicecontainer/Dockerfile
- tests/test-files/test-general-buildx.yaml
- tests/test-files/test-general.yaml
- tests/test-files/test-services.yaml
Creates a network for the step containers, enabling communication between all containers associated with the step
> XENG-8909 Create docker network for step containers

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/build.yaml
> Add python 3.12 to build tests

- .github/workflows/build.yaml
> Improve build steps

- examples/build/secrets/buildrunner.yaml
- examples/build/secrets/platforms-buildrunner.yaml
> Small update to example file docs

- buildrunner/config/models.py
- buildrunner/docker/multiplatform_image_builder.py
- docs/global-configuration.rst
- examples/build/builders/README.rst
- examples/build/builders/buildrunner.yaml
- examples/build/builders/create_builders.sh
- examples/build/builders/global-config-list.yaml
- examples/build/builders/global-config.yaml
- examples/build/builders/remove_builders.sh
- tests/test_config_validation/test_global_config.py
> Buildx builders
